### ISSUE TITLE
bruig: pm tab after receiving an invite greys out

### ISSUE THREAD

**Issue by karamble** [companyzero/bisonrelay#109]
I have setup a brand new account and have exchanged an invite to add my first contact to my addressbook.

The user appears in my user-list in the gui and i start interacting. As soon this user invites me to his group chat (welcome) the complete private message tab greys out and becomes unreadable. Newly received messages appear at the bottom of the tab. As soon i write an answer the tab becomes grey again.

Looks like a conflict with the "accept invite" popup. From an UX perspective having a modal could be a solution instead injecting the popups in the messaging-tabs directly. if they get injected into the message-list it should be in the message-flow like a regular message, this would even enable to have a history at what point in time the invite was received.

**Comment by alexlyp** [comment]
Is this still occurring after the recent updates to chat lists in v0.1.4 ?

**Comment by alexlyp** [comment]
Should be fixed.
