### ISSUE TITLE
Unable to create an inbound channel

### ISSUE THREAD

**Issue by PhoenixGreen** [companyzero/bisonrelay#121]
For the past week, or so, I've been unable to create an inbound channel. I've tried closing all channels and restarting Bison Relay. I've also waited until the outbound channel becomes active before trying to open the inbound channel. I'm currently running br v0.1.3 on macOS (version13.2) 

Here's the error message:
<img width="872" alt="Screenshot 2023-02-07 at 17 41 45" src="https://user-images.githubusercontent.com/186224/217326002-7ca226cb-e8eb-444f-85a8-7556684ae9f9.png">

**Comment by alexlyp** [comment]
Are you still having this issue?

**Comment by PhoenixGreen** [comment]
I was not able to resolve this issue. I tested with two br accounts both on different machines. One of the accounts works fine both inbound and outbound channels. The second account only works for the outbound channel, I was unable to connect an inbound channel using the default channel setup.

As a work around, I have managed to connect my inbound channel to the dcrhive LN hub which currently works without issue, even though it says inactive.
<img width="632" alt="Screenshot 2023-03-14 at 22 01 51" src="https://user-images.githubusercontent.com/186224/225151288-79a80ce4-3547-4729-a0b7-00c381a73d92.png">

**Comment by PhoenixGreen** [comment]
Sorry should have closed this a while ago. All fixed!
