### ISSUE TITLE
bruig: Make notifications more prominent

### ISSUE THREAD

**Issue by davecgh** [companyzero/bisonrelay#15]
While the current red dot next to elements looks nice, it is not visible when you have enough items such that the relevant item is not visible in the current view (aka it's scrolled out of view).  I also personally find it a bit hard to see on high resolution displays (such as 1440p and 4k).  I would suggest all of the following:

1) Make the affected item bold in addition to the dot next to it
2) Add a "Rooms" and "People" header to the two relevant panes under "Chats" and put an indicator next to the text in the appropriate header
3) Put an indicator in the overall tab view on the left for "Chats" or "News Feed" whenever an item relevant to that section has activity.

The combination of these three things should make it much more prominent that there is activity as well as aid in quickly finding it.

**Comment by alexlyp** [comment]
I believe most of these things have been implemented already as described.  Soon we will be merging the User/Rooms lists so issue 2 won't really apply anymore.  Closing.
