### ISSUE TITLE
bruig: replace show*Snackbar with model

### ISSUE THREAD

**Issue by miki-totefu** [companyzero/bisonrelay#152]
show{error,success}Snackbar(context, msg) after async calls may trigger exceptions due to component having been umounted

this needs to change to delivering the msg to a snackbar/notifications model that creates the snackbar at the top level component

**Comment by tiagoalvesdulce** [comment]
I'm interested in working on this.

Looking at the [Flutter docs](https://docs.flutter.dev/release/breaking-changes/scaffold-messenger) I found out:

> By calling Scaffold.of(context).showSnackBar, the current Scaffold would animate a SnackBar into view. This would only apply to the current Scaffold, and would not persist across routes if they were changed in the course of the SnackBars presentation. This would also lead to errors if showSnackBar would be called in the course of executing an asynchronous event, and the BuildContext became invalidated by the route changing and the Scaffold being disposed of.
> The ScaffoldMessenger now handles SnackBars in order to persist across routes and always be displayed on the current Scaffold.

I see the code already uses `ScaffoldMesseger`:

https://github.com/companyzero/bisonrelay/blob/c2d0aaf368db1d37855b30d09d0775cc2aad78b6/bruig/flutterui/bruig/lib/components/snackbars.dart#L5

IIUC,`ScaffoldMessenger` should handle this unmount issue on route change and async actions. Can you provide some reproduction steps?
