### ISSUE TITLE
GUI: v0.1.7-rc1 about version is incorrect

### ISSUE THREAD

**Issue by davecgh** [companyzero/bisonrelay#214]
Clicking on the "About Bison Relay" icon in rc1 of v0.1.7 shows 1.0.0 instead of the correct version.

![image](https://user-images.githubusercontent.com/2115102/233884156-b0d24ea6-46c2-4cbb-b78e-ec98fe0802d2.png)

**Comment by jzbz** [comment]
Wrong version and the white outline is too small on Linux.

![Screenshot_20230423_221019](https://user-images.githubusercontent.com/4731927/233884493-e9a86f9d-7050-46e6-815d-2a0e78880106.png)

**Comment by alexlyp** [comment]
@jzbz I'm having trouble replicating this.  It looks like the screen is a bit "thinner" than normal size.  Does it look normal when you expand the window to the right?

**Comment by jzbz** [comment]
Even in full screen the issue persists.

**Comment by alexlyp** [comment]
Hrm ok

**Comment by davecgh** [comment]
This version part of this is resolved with the final 0.1.7 bins.
