### ISSUE TITLE
No option to scroll down when setting up inbound capacity (screenshot)

### ISSUE THREAD

**Issue by exitus1** [companyzero/bisonrelay#286]
Ok, so I was deeply confused on how to setup an inbound channel. I have a habit of using messaging apps in windowed mode. As per my screenshot, I thought this was all the info presented in the window. I accidentally went full screen and saw there was an option to actually fund the channel.

Anyhow, it would be nice if there was a scroll bar on the side to show the user there is more to the page.

![image](https://github.com/companyzero/bisonrelay/assets/46197055/9bed8bff-c3db-4d15-9634-05d85f390b9e)

**Comment by alexlyp** [comment]
hrm which version are you currently on?  i see a slightly different version of the page you see above and i see the scroll bar on the right as expected.  

Well i suppose i don't see an explicit scroll bar, but i can scroll down as expected.  is that what you mean?

**Comment by exitus1** [comment]
I'm on 0.1.7 on Windows

Scrolling down via the mouse wheel doesn't work for me.

**Comment by alexlyp** [comment]
OK hrm maybe the issue has been resolved overall then.  Can't replicate that issue on master currently.  We did just merge a PR that shrinks the required vertical space of those pages so maybe you won't need to scroll down anymore.  I'll hold off closing this issue until you can verify with 0.1.8 when it gets out.

**Comment by alexlyp** [comment]
Should be resolved now.
