### ISSUE TITLE
Feature screenshot on first page 

### ISSUE THREAD

**Issue by Tsunekazu** [companyzero/bisonrelay#294]
Instead of just text, it would be more appealing to feature a screenshot on the website. But perhaps we can do this as soon as we feel UI is ready or when mobile is out.

**Comment by alexlyp** [comment]
https://github.com/companyzero/bisonrelay-web

More appropriate to be mentioned here.

**Comment by Tsunekazu** [comment]
> https://github.com/companyzero/bisonrelay-web
> 
> More appropriate to be mentioned here.

Yes, I thought I was posting it there. I apologize.
