### ISSUE TITLE
Change messaging from "social media"

### ISSUE THREAD

**Issue by Tsunekazu** [companyzero/bisonrelay#295]
I think alternative to social media makes one think it's "another Twitter" but this isn't precise for two reasons: 1) it's much more than that... It's a whole communication suite, it's a new internet almost. And 2) even in its current form I think it's used more as a Telegram alternative than as a Twitter alternative. What I mean is, we want to tell people they can use this as an encrypted chat app also, and if we put "social media" this doesn't come across

**Comment by alexlyp** [comment]
Where are you recommending these changes?  This repo is for the codebase itself, not really related to marketing of BR.

**Comment by alexlyp** [comment]
https://github.com/companyzero/bisonrelay-web

**Comment by Tsunekazu** [comment]
> Where are you recommending these changes? This repo is for the codebase itself, not really related to marketing of BR.

My bad, I thought I was posting them there.
