### ISSUE TITLE
bruig: Out of order news feed

### ISSUE THREAD

**Issue by jzbz** [companyzero/bisonrelay#357]
This may be related to my use of the "reset all old KX" option yesterday.

Items in the news feed are not in proper chronological order.
We might also want to consider having options to sort the feed by most recent post as well as by most recent activity (comments).

![image](https://github.com/companyzero/bisonrelay/assets/4731927/0600d6c0-d407-4466-b55f-58163202bc69)

**Comment by alexlyp** [comment]
Currently the sorting is based on last activity.   Things like new comments or a new post being received.  And keep in mind that when a post is 'received' that is the time that it exists to you.

**Comment by jzbz** [comment]
Got it, thanks, so my broken ratchet with jy-p made his old post "new" to me which explains it.
