### ISSUE TITLE
bruig: Erroneously claims wallet funds are needed on every restart

### ISSUE THREAD

**Issue by davecgh** [companyzero/bisonrelay#41]
![image](https://user-images.githubusercontent.com/2115102/208144314-7822f0f6-89bd-48c5-8924-446e7e315f64.png)

**Comment by alexlyp** [comment]
I believe this issue is no longer present, let's confirm with 0.1.4 and close/revisit accordingly.

**Comment by davecgh** [comment]
Just did an upgrade to 0.1.7-rc1 and saw this when it started:

![image](https://user-images.githubusercontent.com/2115102/233735404-efb33182-a6b5-491e-8173-6e3850e8bfbc.png)


It does eventually go away once any upgrade happens and the network comes up fully.

**Comment by davecgh** [comment]
I should note that the initial issue is resolved however.  I'll go ahead and open a new one for this.
