### ISSUE TITLE
cli: change pages view keybindings

### ISSUE THREAD

**Issue by behindtext** [companyzero/bisonrelay#419]
the keybindings for the pages view are clunky and would work much better if it was similar to the chat bindings.

current bindings are

- navigate page with ctrl-up and ctrl-dn
- press a button/link with ctrl-v

better bindings are

- scroll page with pgup and pgdn
- navigate buttons/links with up and dn
- press a button/link with enter or similar

this is part of getting cms service into production for next release

**Comment by dajohi** [comment]
Closed by #433
