### ISSUE TITLE
bruig: Chat history is cleared on restart

### ISSUE THREAD

**Issue by davecgh** [companyzero/bisonrelay#49]
As the title indicates, restarting the GUI clears all chat history.  It should automatically be available on reload.

I'm aware the information is in the logs on the file system, but that is not very user friendly or expected from a GUI.

I've seen several people comment about this.

**Comment by davecgh** [comment]
I would also add that this really should only dynamically load the most recent entries the first time a group chat is accessed and then dynamically load older entries if the user scrolls back in history far enough.

Similarly, once a chat reaches a certain number of entries, it should automatically unload all entries far enough back in history to prevent more and more memory being consumed while in operation.

The combination of these things will mean that it doesn't have to load up a ton of stuff when the client is launched making the launch slow and similarly it will prevent high memory usage that would otherwise result from loading potentially years of history for every chat.

**Comment by alexlyp** [comment]
Closed with #230
