### ISSUE TITLE
Windows AppData being set to something strange

### ISSUE THREAD

**Issue by alexlyp** [companyzero/bisonrelay#6]
for Users that are using the msix it appears the appdata location for bruig they are given is rouhgly "%LOCALAPPDATA%\Packages\decred.br.gui_ywj3797w5q8tj\LocalCache\Local\bruig"  instead of just "%LOCALAPPDATA%\bruig"

**Comment by davecgh** [comment]
It looks like this moved in version 0.1.3 to `%LOCALAPPDATA%\Packages\com.flutter.bruig_ywj3797wkq8tj` which is still incorrect and also means the existing setup is not detected leading to the upgraded version wanting to do a full setup again:

![image](https://user-images.githubusercontent.com/2115102/213814621-9668fc55-927b-45df-9160-6845f898a76e.png)

**Comment by alexlyp** [comment]
I've opened an issue with the msix tool repo, so hopefully we can get some guidance on how to fix or proceed.  https://github.com/YehudaKremer/msix/issues/173

Once the location is 'fixed' to the %LOCALAPPDATA%/bisonrelay we'll figure out how to move the locations to have a seamless experience for older versions.
