### ISSUE TITLE
bruig: Address generation exceeding gap limit and leaves GUI/wallet in an unrecoverable state

### ISSUE THREAD

**Issue by davecgh** [companyzero/bisonrelay#70]
Somewhat related to #11, during the initial setup phase, the GUI instructs you to create an inbound channel while you already have an outbound in the pending state, it results in the `channel creation policy error: already has pending open channel request` error described in #11.

However, a much bigger issue is that it also continues to generate new addresses that are never used with each attempt and as a result ultimately leads to exceeding the gap limit of unused addresses which leaves the wallet in an unrecoverable state.  See the next screenshot:

![image](https://user-images.githubusercontent.com/2115102/209269653-17c23107-7621-419b-92d8-39021e523a62.png)

Next, when you try to open an inbound channel anyway (since it doesn't prevent you despite the error obtaining a new address), the GUI then goes on to erroneously report that there is already a pending channel request despite it very clearly showing that there is only 1 active channel and 0 pending.  See the next screenshot:

![image](https://user-images.githubusercontent.com/2115102/209269868-2b7d3ce0-ab22-40be-a27c-36cbd939f909.png)

**Comment by alexlyp** [comment]
Is this still occurring @davecgh ?  I believe it will only show the funds needs screen if the wallet doesn't properly connect to the network, but typically goes away quickly.

**Comment by davecgh** [comment]
I'll have to do some testing with opening a new channel on a fresh instance to say since it really only happened then iirc.

**Comment by alexlyp** [comment]
I believe this should be fixed with changes from dcrlnd.
