### ISSUE TITLE
Expose basic mainnet Decred wallet functionality

### ISSUE THREAD

**Issue by jzbz** [companyzero/bisonrelay#74]
As discussed in the #br channel, having send/receive functionality for mainnet Decred accessible will give use a working mobile wallet once again, as well as a simple desktop alternative to Decrediton.

**Comment by davecgh** [comment]
This might be resolved as of 0.1.7.  There is now the ability to receive and send on-chain under the "LN Management -> On-Chain" tab.

![image](https://user-images.githubusercontent.com/2115102/234425597-52f315bd-5058-4196-80e0-70ddf3e51dd9.png)
