### ISSUE TITLE
feature: hide messages that contain a string

### ISSUE THREAD

**Issue by sumiflow** [companyzero/bisonrelay#99]
We now have a working "brbot" that bridges messages between BR and matrix.
The issue I have is that accounts I have /ignored on matrix now come through to BR via the brbot.   Each user has their own preference of matrix /ignored accounts.
One such account that I have /ignored on matrix is the "@bridge:decred.org" account which bridges messages between telegram/discord and matrix.  This is so that I don't see any telegram/discord messages on matrix and that's the way I like it.  The issue for me now is that those ignored telegram/discord messages are coming through to BR via brbot.  Simply ignoring the entire brbot account on BR would not work for me since that would block all matrix messages as well, when I really only want to block messages from the telegram/discord bridge.

One suggested way to solve this is to add the ability for each user to hide messages in BR that contain user-specified strings.
Perhaps I could issue a command in BR, something along the lines of:
/ignoreText "<@bridge:decred.org>"
Which would ignore any messages from any BR user if it contains the text <@bridge:decred.org>
There might also need to be some way to show a list of ignored text entries and "un-ignore" text entries as well.

Blocking encrypted text before it is received is probably not possible, however, the bruig client could hide the text after it has been received/decrypted but before it is shown in the UI.

**Comment by karamble** [comment]
An ignore function based on strings would be sufficient and if possible additionally with RegEx functionality

**Comment by alexlyp** [comment]
Completed.
